In [34]:
from bs4 import BeautifulSoup
import re
import glob
import os
import requests
from pathlib import Path
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from pathlib import Path
import pandas as pd
import glob
from nltk.corpus import stopwords

In [35]:
def get_links_and_dates():
    links_txt_path = 'data/links.txt'
    with open(links_txt_path, 'r') as links_txt:
        links = links_txt.readlines()

    dates = []
    for link in links:
        file_date = re.sub('https://www.federalreserve.gov/monetarypolicy/fomcminutes', '', link)
        file_date = re.sub('.htm\n', '', file_date)
        dates.append(file_date)
    
    return dates

In [36]:
def webscrape_link(file):
    text_list = []
    page = file.read()
    soup = BeautifulSoup(page, "html.parser")
    text_string = ""
    for info in soup.find_all("p"):
        text_string = text_string + " " + info.get_text()
    text_string = re.sub("\n", " ", text_string)
    text_string = re.sub("\s+", " ", text_string)
    text_list.append(text_string)  
    return text_list

In [30]:
links = []
with open('data/links.txt', 'r') as file:
    for line in file:
        links.append(line.strip())
dates = get_links_and_dates()

for link, date in zip(links, dates):
    page = requests.get(link)
    newsoup = BeautifulSoup(page.content, "html.parser")

    mystring = ""
    for info in newsoup.find_all("p"):
        mystring = mystring + " " + info.get_text()

    mystring = re.sub("\n", " ", mystring)
    mystring = re.sub("\s+", " ", mystring)
    mystring = re.sub("\[.*?\]", " ", mystring)

    cleanedlink = re.sub('/', '', link)
    filename = date + '.txt'

    with open('txtfiles2/' + filename, 'w') as file:
        file.write(mystring)

In [39]:
text_files = glob.glob('txtfiles3/*.txt')
file_names = [Path(text).stem for text in text_files]

In [44]:
stoplist = stopwords.words("english")
stoplist.extend([".", ",", "?", "could", "would", "“", "”", "longer", "developments", "system", "real", "poole", "yields", "banks", "credit", "taf", "’", ";", "!", 's', 'meeting', 'markets', 'financial', 'participants', 'prices', 'economic', 'conditions', 'committee', 'core', 'outlook', 'housing', "'s", 'spending', 'committee', 'remained', 'rate', 'likely', 'also', 'expected', 'consumer', 'quarter', 'data', 'market', 'generally', 'higher', 'period', 'price', 'generally', 'committee', 'june', "''", 'continued', 'progress', 'economy', 'bank', 'reserve', 'june', 'committee\\', 'reserve', ')', 'board', 'division', 'federal', '``', '2', 'goals', 'monetary', 'supply', 'policy', 'u.s.', '(', 'noted', '2022', 'balance', 'percent', 'range', 'treasury', 'activity', 'stance', 'intermeeting', 'recent', 'year', 'time', 'businesses', 'governors', 'appropriate', 'operations', 'support', 'agreed', 'members', '2020', 'director', 'term', 'staff', 'months', '&', 'united', 'states', 'new', 'york', 'achilles', 'sangster', 'annette', 'samuel', 'min', 'michele', 'sylvain', '2-', '5-', 'seth', 'boards', 'met', 'wright', 'met', 'national', 'glenn', 'weekend', 'andrea', 'laura', 'naureen', '737', 'andrew', 'marc', 'ron', 'sally', '1-1/2', '10-', 'ivan', 'april', 'may', 'june', 'july', 'january', 'february', 'march', 'august', 'september', 'october', 'november', 'december', 'purchase', 'year', 'level', 'net', 'firm', 'still', 'judged', 'many', 'observed', 'sector', 'well'])

tfidf_vectorizer = TfidfVectorizer(input='filename', stop_words=stoplist)
tfidf_vector = tfidf_vectorizer.fit_transform(text_files)

/opt/homebrew/lib/python3.11/site-packages/sklearn/feature_extraction/text.py:408: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['10'] not in stop_words.
  warnings.warn(

In [45]:
tfidf_df = pd.DataFrame(tfidf_vector.toarray(), index=file_names, columns=tfidf_vectorizer.get_feature_names_out())
tfidf_df.stack().reset_index()
tfidf_df = tfidf_df.stack().reset_index()
tfidf_df = tfidf_df.rename(columns={0:'tfidf', 'level_0': 'document','level_1': 'term', 'level_2': 'term'})
tfidf_df.sort_values(by=['document','tfidf'], ascending=[True,False]).groupby(['document']).head(10)

      document        term     tfidf
52473     2007   inflation  0.399868
52058     2007      growth  0.346300
54272     2007   pressures  0.146636
55054     2007       risks  0.122287
50423     2007  correction  0.121503
...        ...         ...       ...
76415     2023      growth  0.132557
79411     2023       risks  0.124386
76258     2023       funds  0.101688
80478     2023  tightening  0.096240
73415     2023     adviser  0.085424

[170 rows x 3 columns]

In [108]:
top_tfidf = tfidf_df.sort_values(by=['document','tfidf'], ascending=[True,False]).groupby(['document']).head(5)

In [48]:
top_tfidf[top_tfidf['term'].str.contains('risk')]

      document   term     tfidf
55054     2007  risks  0.122287
95649     2008  risks  0.107546
79411     2023  risks  0.124386

In [109]:
top_tfidf[top_tfidf['term'].str.contains('growth')]

       document    term     tfidf
52058      2007  growth  0.346300
92653      2008  growth  0.256168
35820      2010  growth  0.139926
43939      2011  growth  0.141428
68296      2012  growth  0.176273
27701      2014  growth  0.171327
19582      2015  growth  0.150506
3344       2016  growth  0.179316
133248     2018  growth  0.195025
125129     2019  growth  0.202284
84534      2022  growth  0.130309